# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94fee29d4a8039200c4bfee54106dbe4e87cb89de6c18069947ff514223c3cca42746695f5dbfc1fbdbc7993e4463c0b2d58e4843811469159a91022d9c6b93a

test:
  secret_key_base: 91d2677a4f2ce25248400073381a89141e2d5f0ff7145f667c9ae51d3f02cee861dd41f1535b6904f35eea0bc0d9d75622394ddf7461521748b51194c9dae991

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
